import Head from "next/head";
import Image from "next/image";
import NewsList from "../components/NewsList";
import styles from "../styles/Home.module.css";

export default function Home({ posts }) {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header className="text-5xl px-3 py-14 md:max-w-[50%] mx-auto">
				Your best news provider at your door step
			</header>
			<NewsList posts={posts} />
			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}

export const getStaticProps = async () => {
	try {
		const res = await fetch("https://api.spaceflightnewsapi.net/v3/blogs");
		const posts = await res.json();
		return {
			props: {
				posts,
			},
		};
	} catch (error) {
		console.log(error);
	}
};
